### PR TITLE
Bug Fix: different web hook resource versions

### LINKED ISSUE #91: Unable to cast object of type 'System.String' to type 'Microsoft.VisualStudio.Services.WebApi.IdentityRef'.
Updated to 0.9.8

Getting "Warning" on each call:

`2020-01-02T12:04:18.471 [Warning] Rule 'Project_MSDAX_Rules' failed: Unable to cast object of type 'System.String' to type 'Microsoft.VisualStudio.Services.WebApi.IdentityRef'.`

Rule:

```
.language=C#
.import=System
.import=System.Collections
.import=System.Collections.Generic

logger.WriteInfo($"Work Item Id: #{ self.Id }");

if(self.WorkItemType == "Bug" || self.WorkItemType == "Product Backlog Item")
{
    foreach (var child in self.Children) {
        if (child.WorkItemType == "Task") {

            if(self["Microsoft.VSTS.Common.Priority"] != child["Microsoft.VSTS.Common.Priority"])
            {
                child["Microsoft.VSTS.Common.Priority"] = self["Microsoft.VSTS.Common.Priority"];
                logger.WriteInfo("Priority updated");
            }

            if(self["HABA.Category"] != child["HABA.Category"])
            {
                child["HABA.Category"] = self["HABA.Category"];
                logger.WriteInfo("Category updated");
            }
        }
    }
}

if(self.WorkItemType == "Bug" || self.WorkItemType == "Product Backlog Item" || self.WorkItemType == "Issue")
{
    foreach (var child in self.Children) {
        if (child.WorkItemType == "Task") {
            if(self.AreaPath != child.AreaPath)
            {
                child.AreaPath = self.AreaPath;
                logger.WriteInfo("Area updated");
            }

            if(self.IterationPath != child.IterationPath)
            {
                if(child.State != "Removed" && child.State != "Done") {
                    child.IterationPath = self.IterationPath;
                    logger.WriteInfo("Iteration updated");
                }
            }
        }
    }
}

var parent = self.Parent;

if (parent != null && (parent.WorkItemType == "Bug" || parent.WorkItemType == "Product Backlog Item" || parent.WorkItemType == "Issue")) 
{
    parent["Microsoft.VSTS.Scheduling.CompletedWork"] = parent.Children.Sum(task => task.GetFieldValue<double>("Microsoft.VSTS.Scheduling.CompletedWork", 0d));
    logger.WriteInfo("CompletedWork cumulated");
}

Where is my issue?

```

### LINKED ISSUE #92: Relations are missing
Version: 0.9.8

Script:

```
.language=C#
.import=System
.import=System.Collections
.import=System.Collections.Generic

logger.WriteInfo($"Work Item Id: #{ self.Id }");

logger.WriteInfo($"Relations: {self.RelationLinks.Count()}");

var self2 = store.GetWorkItem(self.Id.Value);

logger.WriteInfo($"Relations: {self2.RelationLinks.Count()}");

if(self.WorkItemType == "Bug" || self.WorkItemType == "Product Backlog Item")
{
    var children = self.Children;

    foreach (var child in children) {
        if (child.WorkItemType == "Task") {

            
            if(self["Microsoft.VSTS.Common.Priority"] != child["Microsoft.VSTS.Common.Priority"])
            {
                child["Microsoft.VSTS.Common.Priority"] = self["Microsoft.VSTS.Common.Priority"];
                logger.WriteInfo("Priority updated");
            }

            if(self["HABA.Category"] != child["HABA.Category"])
            {
                child["HABA.Category"] = self["HABA.Category"];
                logger.WriteInfo("Category updated");
            }
        }
    }
}

if(self.WorkItemType == "Bug" || self.WorkItemType == "Product Backlog Item" || self.WorkItemType == "Issue")
{
    var children = self.Children;

    foreach (var child in children) {
        if (child.WorkItemType == "Task") {
            if(self.AreaPath != child.AreaPath)
            {
                child.AreaPath = self.AreaPath;
                logger.WriteInfo("Area updated");
            }

            if(self.IterationPath != child.IterationPath)
            {
                if(child.State != "Removed" && child.State != "Done") {
                    child.IterationPath = self.IterationPath;
                    logger.WriteInfo("Iteration updated");
                }
            }

            if(self["Custom.CostCenter"] != child["Custom.CostCenter"])
            {
                if(child.State != "Removed" && child.State != "Done") {
                    child["Custom.CostCenter"] = self["Custom.CostCenter"];
                    logger.WriteInfo("Cost Center updated");
                }
            }
        }
    }
}

var parent = self.Parent;

if (parent != null && (parent.WorkItemType == "Bug" || parent.WorkItemType == "Product Backlog Item" || parent.WorkItemType == "Issue")) 
{
    
    parent["Microsoft.VSTS.Scheduling.CompletedWork"] = parent.Children.Sum(task => task.GetFieldValue<double>("Microsoft.VSTS.Scheduling.CompletedWork", 0d));
    logger.WriteInfo("CompletedWork cumulated");
}

return "Finished";


```
Cloud call:
```
2020-01-03T09:01:04.560 [Information] Executing 'Functions.Project_MSDAX_Rules' (Reason='This function was programmatically called via the host APIs.', Id=b0761fdc-5b66-44ab-83a5-317c9e25f41c)
2020-01-03T09:01:04.568 [Information] Aggregator v0.9.0+local.development executing rule 'Project_MSDAX_Rules'
2020-01-03T09:01:04.927 [Information] Connected to Azure DevOps
2020-01-03T09:01:04.944 [Information] Initial WorkItem 60627 retrieved from https://dev.azure.com/HABAGROUP/
2020-01-03T09:01:06.039 [Information] Work Item Id: #60627
**2020-01-03T09:01:06.040 [Information] Relations: 0
2020-01-03T09:01:06.040 [Information] Relations: 0**
2020-01-03T09:01:06.041 [Information] No changes saved to Azure DevOps.
2020-01-03T09:01:06.041 [Information] Finished
2020-01-03T09:01:06.041 [Information] Returning 'Finished' from 'Project_MSDAX_Rules'
2020-01-03T09:01:06.042 [Information] Executed 'Functions.Project_MSDAX_Rules' (Succeeded, Id=b0761fdc-5b66-44ab-83a5-317c9e25f41c)
```

Local run works fine:

`invoke.rule --dryrun --project "Microsoft Dynamics AX" --event workitem.updated --workItemId 60627 --local --source test\Project_MSDAX_Rules.rule --impersonate`

```
[2020-01-03 10:00:01Z] Aggregator CLI v0.9.0+local.development (build: 0.9.0.0 Release) (c) TFS Aggregator Team
[2020-01-03 10:00:01Z] Connected to subscription 03d4a655-31fb-4dd0-9687-fe74dc238abf
[2020-01-03 10:00:01Z] Connected to dev.azure.com
[2020-01-03 10:00:02Z] Connected to Azure DevOps
[2020-01-03 10:00:02Z] Project Microsoft Dynamics AX data read.
[2020-01-03 10:00:02Z] Initial WorkItem 60627 retrieved from https://dev.azure.com/habagroup
[2020-01-03 10:00:03Z] Work Item Id: #60627
[2020-01-03 10:00:03Z] Relations: 1
[2020-01-03 10:00:03Z] Relations: 1
[2020-01-03 10:00:03Z] Loading workitem 60626
[2020-01-03 10:00:04Z] CompletedWork cumulated
[2020-01-03 10:00:04Z] Dry-run mode: no updates sent to Azure DevOps.
[2020-01-03 10:00:04Z] Found a request to update workitem 60626 in Microsoft Dynamics AX
[2020-01-03 10:00:04Z] Dry-run mode: no updates sent to Azure DevOps.
[2020-01-03 10:00:04Z] Changes saved to Azure DevOps (mode Default): 0 created, 1 updated.
[2020-01-03 10:00:04Z] Rule returned 'Finished'
[2020-01-03 10:00:04Z] Succeeded
```

Where is my issue?

### LINKED ISSUE #99: Error with retrieve a workitem with attachment
image

Occurs when a workitem have a relation to an attachment.

```csharp
aggregator.Engine.WorkItemRelationWrapper.WorkItemRelationWrapper(string relationUrl)

var id = int.Parse(relationUri.Segments.Last());
LinkedId = new PermanentWorkItemId(id);
```
In this case, the last segment is not an integer but a guid.

I proposed this fix (before to do a wrong pull request >.<) :
```csharp
aggregator.Engine.WorkItemRelationWrapperCollection.WorkItemRelationWrapperCollection(WorkItemWrapper workItem, IList<WorkItemRelation> relations)

_original = relations == null
                        ? new List<WorkItemRelationWrapper>()
                        : relations.Where(relation => 
                                            !relation.Rel.Equals("ArtifactLink") 
                                            && !relation.Rel.Equals("AttachedFile")
                                            && !relation.Rel.Equals("Hyperlink"))
                                   .Select(relation => new WorkItemRelationWrapper(relation))
                                   .ToList();
```

### PR DESCRIPTION
**Pull request by BobSilent**
Fixes #91, Fixes #92 and (quick fix) Fixes #99.
For #92 please change back Resource Version to 1.0, as in all other Versions there is a bug that the relations are not send in the the hook event data.

### CODE REVIEW

**Comment by Eckham** [comment]
The fixes works fine. Thx.

**Comment by adu80** [comment]
The fixes works perfectly, thank you very much @BobSilent

**Comment by rotda** [comment]
When will be PR merged ? Than I can build, without that our rules not working anymore

**Comment by BobSilent** [comment]
give us a little bit of time @giuliov is currently heavily busy, in the meanwhile you could build this PR branch to get the version.

the plan is to release a bugfix version quite soon

**Comment by rotda** [comment]
Hi Bob ,

in which folder I must copy the FunctionRuntime.zip that the cli upload the version to azure ?

**Comment by BobSilent** [comment]
With the `install.instance` command you can specify a `sourceUrl` parameter where you can use the path to your zip.
If you add `--verbose` you see a little more output when updating, only for the case that you need to update version number of your created zip

**Comment by rotda** [comment]
@BobSilent I have not updated the Runtime but now I get an error at

`var children = parent.Children;`

```
[2020-01-21 09:35:15Z] Initial WorkItem 97077 retrieved from https://dev.azure.com/
[2020-01-21 09:35:17Z] #################Starting########################################
[2020-01-21 09:35:17Z] Loading workitem 43350
[2020-01-21 09:35:17Z] #################1########################################
[2020-01-21 09:35:17Z] #################2########################################
[2020-01-21 09:35:17Z] #################Backlog########################################
[2020-01-21 09:35:17Z] Loading workitems 101333,60909,95799,54329,101287,65658,44467,58865,43351,58580
[2020-01-21 09:35:17Z] Input string was not in a correct format.
```

**Comment by rotda** [comment]
It seems not all the item have this problem , some work some not.
With the old version it was working fine

**Comment by BobSilent** [comment]
unfortunately you are now facing #99, i just added a new commit for it to this pull request.

**Comment by rotda** [comment]
Thx now this problem is fixed.
But the functions returns 406 but there is no error 

```
2020-01-21 15:45:09.746 | Changes saved to Azure DevOps (mode Default): 0 created, 3 updated. | Information
-- | -- | --
2020-01-21 15:45:09.746 | 18 | Information
2020-01-21 15:45:09.746 | Returning '18' from 'test3' | Information
2020-01-21 15:45:09.748 | Executed 'Functions.test3' (Succeeded, Id=252219bd-1a49-453a-bdfe-8809c09dbe3c) | Information


```

**Comment by RSMJreck** [comment]
I'm getting a 406 status as well with a very basic rule that just adds to the description.

**Comment by BobSilent** [comment]
related to #104

**Pull request merged**
