### PR TITLE
Simplify code

### PR DESCRIPTION
**Pull request by BobSilent**
Hi,

i am currently working on a IIS webhook extension based on this code (yes I know you depricated more or less the old version, due to too much complexity) 
nevertheless i want to use your cli as base for my iis implementation, if you want to I can also provide this solution then.

A first step was a small cleanup, hope you like it and merge the changes.

I intentionally left the small changes in seperate commits

### CODE REVIEW

**Comment by giuliov** [comment]
Sorry for late response, but I will need more time to look at this: it's a very busy moment.

**Comment by BobSilent** [comment]
No Problem, just take the time and do not hesitate to comment if I should improve something 😄

**Comment by BobSilent** [comment]
okay, i will re-introduce it, although there is today no usage of it. 
maybe then it would make sense (for future) to encapsulate both Id and Name in an own Data Class or so, otherwise in the apis there are always both values  passed in (which increases the number of parameters)

but that's just an idea. 
I will update the pull request.

**Comment by BobSilent** [comment]
yes, that was my fault, sorry.

**Pull request merged**
